export interface IContent {
    invalid_password: string,
    cancel_message: string,
    requiredField_email: string,
    logonIdentifier_username: string,
    forgotpassword_link: string,
    local_intro_email: string,
    invalid_email: string,
    createaccount_link: string,
    unknown_error: string,
    requiredField_username: string,
    logonIdentifier_email: string,
    email_pattern: string,
    requiredField_password: string,
    password: string,
    divider_title: string,
    createaccount_intro: string,
    social_intro: string,
    button_signin: string,
    local_intro_username: string
}